import os
import sys
import math
import numpy as np
import torch
import torch.nn as nn
import logging

_logger = logging.getLogger(__name__)


def resize_pos_embed(posemb, posemb_new, num_tokens=1, gs_new=()):
    # Rescale grid of position embeddings when loading from state_dict
    _logger.info('Resized position embedding: %s to %s', posemb.shape, posemb_new.shape)
    ntok_new = posemb_new.shape[1]
    if num_tokens:
        posemb_tok, posemb_grid = posemb[:, :num_tokens], posemb[0, num_tokens:]
        ntok_new -= num_tokens
    else:
        posemb_tok, posemb_grid = posemb[:, :0], posemb[0]
    gs_old = int(math.sqrt(len(posemb_grid)))
    if not len(gs_new):  # backwards compatibility
        gs_new = [int(math.sqrt(ntok_new))] * 2
    assert len(gs_new) >= 2
    _logger.info('Position embedding grid-size from %s to %s', [gs_old, gs_old], gs_new)
    posemb_grid = posemb_grid.reshape(1, gs_old, gs_old, -1).permute(0, 3, 1, 2)
    posemb_grid = nn.functional.interpolate(posemb_grid, size=gs_new, mode='bicubic', align_corners=False)
    posemb_grid = posemb_grid.permute(0, 2, 3, 1).reshape(1, gs_new[0] * gs_new[1], -1)
    posemb = torch.cat([posemb_tok, posemb_grid], dim=1)
    return posemb


def get_stats(modality):
    stats = {"MRI": [(0.17368862, 0.17368862, 0.17368862), (0.16198656, 0.16198656, 0.16198656)],
             "Fundus": [(0.423737496137619, 0.2609460651874542, 0.128403902053833),
                        (0.29482534527778625, 0.20167365670204163, 0.13668020069599152)],
             "UBM": [(0.096110865, 0.096110865, 0.096110865), (0.20977867, 0.20977867, 0.20977867)],
             "Ultrasound": [(0.05989236, 0.05978666, 0.056694973), (0.154277, 0.15504874, 0.14464583)],
             "External": [(0.4936253, 0.36324808, 0.25956994), (0.32001, 0.27109432, 0.21991591)],
             "FFA": [(0.2020487, 0.20205145, 0.20201068), (0.17406046, 0.17404206, 0.17401208)],
             "SlitLamp": [(0.5556667, 0.40288574, 0.38857886), (0.26516676, 0.23311588, 0.23903583)],
             "OCT": [(0.21091926, 0.21091926, 0.21091919), (0.17598894, 0.17598891, 0.17598893)]}
    assert modality in stats.keys(), f'unsupported modality: {modality}'
    return stats[modality]


def load_pretrained_weights(model, pretrained_weights, checkpoint_key, model_name, patch_size):
    if os.path.isfile(pretrained_weights):
        state_dict = torch.load(pretrained_weights, map_location="cpu")
        if checkpoint_key is not None and checkpoint_key in state_dict:
            print(f"Take key {checkpoint_key} in provided checkpoint dict")
            state_dict = state_dict[checkpoint_key]
        # remove `module.` prefix
        state_dict = {k.replace("module.", ""): v for k, v in state_dict.items()}
        # remove `backbone.` prefix induced by multicrop wrapper
        state_dict = {k.replace("backbone.", ""): v for k, v in state_dict.items()}

        # position embedding
        pos_embed_w = state_dict['pos_embed']
        if pos_embed_w.shape != model.pos_embed.shape:
            print(f"will reisze pos_embed from {pos_embed_w.shape} to {model.pos_embed.shape}")
            pos_embed_w = resize_pos_embed(pos_embed_w, model.pos_embed, getattr(model, 'num_tokens', 1),
                                           model.patch_embed.grid_size)
            state_dict['pos_embed'] = pos_embed_w

        msg = model.load_state_dict(state_dict, strict=False)
        print('Pretrained weights found at {} and loaded with msg: {}'.format(pretrained_weights, msg))
        return
    else:
        print(f"Pretrained weights file not found: {pretrained_weights}")


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using inverse CDF for normal distribution.
        # Get upper and lower cdf values
        l = a - 2 * std
        u = b + 2 * std

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in proper range
        tensor.clamp_(min=a, max=b)
        return tensor
